import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'fr' | 'en';

const translations = {
  fr: {
    nav: {
      dashboard:   'Dashboard',
      personnel:   'Personnel',
      presence:    'Fiches Présence',
      constraints: 'Contraintes',
      calculation: 'Calcul',
      history:     'Historique',
      settings:    'Paramètres',
    },
    common: {
      save:       'Enregistrer',
      cancel:     'Annuler',
      delete:     'Supprimer',
      export:     'Exporter',
      search:     'Rechercher...',
      loading:    'Chargement...',
      noData:     'Aucune donnée',
      back:       'Retour',
    },
    settings: {
      title:          'Paramètres',
      subtitle:       'Gérer les préférences de votre compte',
      profile:        'Profil Utilisateur',
      fullName:       'Nom complet',
      email:          'Email',
      role:           'Rôle',
      notifications:  'Notifications',
      emailNotif:     'Notifications Email',
      emailNotifSub:  'Recevoir des alertes par email',
      pushNotif:      'Notifications Push',
      pushNotifSub:   'Recevoir des notifications instantanées',
      weeklyReport:   'Rapport Hebdomadaire',
      weeklyReportSub:'Recevoir un rapport chaque semaine',
      appearance:     'Apparence',
      theme:          'Thème',
      themeLight:     'Clair',
      themeDark:      'Sombre',
      language:       'Langue',
      security:       'Sécurité',
      changePassword: 'Changer le mot de passe',
      enable2FA:      "Activer l'authentification à deux facteurs",
      logoutAll:      'Déconnecter tous les appareils',
      saveBtn:        'Enregistrer les modifications',
      savedMsg:       'Paramètres enregistrés avec succès!',
      version:        'Version',
      lastUpdate:     'Dernière mise à jour',
      licence:        'Licence',
    },
    dashboard: {
      title:        'Tableau de bord',
      subtitle:     'Vue globale de votre activité RH',
      payroll:      'Masse salariale',
      sales:        'Ventes totales',
      commissions:  'Commissions',
      calculations: 'Calculs effectués',
      salesEvol:    'Évolution des ventes',
      recentActivity:'Activité récente',
      topPerformers:'Top Performers',
      commissionsMonth:'Commissions / Mois',
    },
    history: {
      title:       'Historique des calculs',
      subtitle:    'Consultez et gérez tous les calculs effectués',
      noHistory:   'Aucun calcul enregistré',
      noHistorySub:'Effectuez votre premier calcul pour le voir apparaître ici.',
      exportPDF:   'Export PDF',
      clearAll:    'Tout effacer',
      search:      'Rechercher un employé...',
      month:       'Mois',
      year:        'Année',
      reset:       'Réinitialiser',
    },
    login: {
      title:    'Bienvenue sur ABC DIS',
      subtitle: 'Système de Gestion RH & Commissions',
      email:    'Adresse email',
      password: 'Mot de passe',
      submit:   'Se connecter',
      loading:  'Connexion...',
      error:    'Email ou mot de passe incorrect',
    },
    constraints: {
      title:          'Gestion des Commissions',
      subtitle:       "Gérez les règles de calcul par carte (Coca Cola, Ferrero, Wall's)",
      newRule:        'Nouvelle Règle',
      searchPlaceholder: 'Rechercher une règle ou une condition...',
      allCards:       'Toutes les Cartes',
      colName:        'Nom',
      colCard:        'Carte',
      colValue:       'Valeur',
      colCondition:   'Condition',
      colStatus:      'Statut',
      colActions:     'Actions',
      noRules:        'Aucune règle trouvée.',
      deleteTitle:    'Supprimer la règle',
      deleteDesc:     "Êtes-vous sûr de vouloir supprimer cette règle ? Cette action est irréversible.",
      cancel:         'Annuler',
      confirmDelete:  'Confirmer la suppression',
      historyTooltip: "Voir l'historique",
      editTooltip:    'Modifier',
      deleteTooltip:  'Supprimer',
    },
    calculation: {
      title:           'Calcul par Marque',
      subtitle:        'Choisissez une marque pour accéder au calcul spécifique ou importez vos données.',
      importBtn:       'Importer un fichier Excel',
      openManagement:  'Ouvrir la gestion',
      sector:          'Secteur Distribution',
      brandDescCoca:   'Gestion des livraisons et commissions pour la gamme Coca-Cola.',
      brandDescWalls:  "Calcul des commissions saisonnières et volume Wall's.",
      brandDescFerrero:'Suivi des objectifs et primes pour les produits Ferrero.',
    },
    personnel: {
      title:          'Gestion du Personnel',
      subtitle:       "Gérez et consultez les profils de l'équipe",
      addProfile:     'Ajouter un profil',
      presenceSheet:  'Fiche de Présence',
      searchByName:   'Rechercher par nom...',
      activeFilter:   'Actifs',
      reset:          'Réinitialiser',
      loading:        'Chargement...',
      noPersonnel:    'Aucun personnel trouvé',
      actif:          'Actif',
      inactif:        'Inactif',
      activate:       'Activer',
      deactivate:     'Désactiver',
      edit:           'Modifier',
      deleteTitle:    'Supprimer ce profil ?',
      deleteDesc:     'Cette action est irréversible. Le profil sera définitivement supprimé.',
      addTitle:       'Ajouter un profil',
      editTitle:      'Modifier le profil',
      formDesc:       'Remplissez les informations du personnel',
      update:         'Mettre à jour',
      add:            'Ajouter',
      matricule:      'Matricule',
      contractType:   'Type de Contrat',
      nom:            'Nom',
      prenom:         'Prénom',
      carte:          'Carte',
      fonction:       'Fonction',
      role:           'Rôle',
      telephone:      'Téléphone',
      ville:          'Ville',
      statut:         'Statut',
      chooseCard:     'Choisir une carte',
      presenceTitle:  'Fiche de Présence',
      presenceDesc:   "Enregistrez la présence des livreurs pour la tournée du jour.",
      truckId:        'Matricule du Camion',
      canal:          'Canal',
      livreur:        'Livreur',
      aide:           'Aide Livreur',
      none:           'Aucun',
      save:           'Enregistrer',
    },
    brandCalc: {
      teamMembers:  "Membres de l'équipe",
      active:       'Actif(s)',
      noCalc:       'Aucun calcul effectué',
      noCalcSub:    'Utilisez le bouton "Lancer le calcul groupé" pour simuler les commissions.',
      launchBtn:    'Lancer le calcul groupé',
      calculating:  'Calcul en cours...',
      detailTab:    'Détail par employé',
      recapTab:     'Récapitulatif global',
      commissions:  'Commissions',
      bonus:        'Bonus',
      penalties:    'Pénalités',
      colEmployee:  'Employé',
      colBase:      'Sal. Base',
      colComm:      'Comm.',
      colBonus:     'Bonus',
      colPenal:     'Pénal.',
      colNet:       'Net',
      teamTotal:    'TOTAL ÉQUIPE',
      back:         'Retour',
    },
  },
  en: {
    nav: {
      dashboard:   'Dashboard',
      personnel:   'Personnel',
      presence:    'Attendance Sheets',
      constraints: 'Constraints',
      calculation: 'Calculation',
      history:     'History',
      settings:    'Settings',
    },
    common: {
      save:       'Save',
      cancel:     'Cancel',
      delete:     'Delete',
      export:     'Export',
      search:     'Search...',
      loading:    'Loading...',
      noData:     'No data',
      back:       'Back',
    },
    settings: {
      title:          'Settings',
      subtitle:       'Manage your account preferences',
      profile:        'User Profile',
      fullName:       'Full name',
      email:          'Email',
      role:           'Role',
      notifications:  'Notifications',
      emailNotif:     'Email Notifications',
      emailNotifSub:  'Receive alerts by email',
      pushNotif:      'Push Notifications',
      pushNotifSub:   'Receive instant notifications',
      weeklyReport:   'Weekly Report',
      weeklyReportSub:'Receive a report every week',
      appearance:     'Appearance',
      theme:          'Theme',
      themeLight:     'Light',
      themeDark:      'Dark',
      language:       'Language',
      security:       'Security',
      changePassword: 'Change password',
      enable2FA:      'Enable two-factor authentication',
      logoutAll:      'Log out all devices',
      saveBtn:        'Save changes',
      savedMsg:       'Settings saved successfully!',
      version:        'Version',
      lastUpdate:     'Last updated',
      licence:        'License',
    },
    dashboard: {
      title:         'Dashboard',
      subtitle:      'Global overview of your HR activity',
      payroll:       'Total payroll',
      sales:         'Total sales',
      commissions:   'Commissions',
      calculations:  'Calculations done',
      salesEvol:     'Sales evolution',
      recentActivity:'Recent activity',
      topPerformers: 'Top Performers',
      commissionsMonth:'Commissions / Month',
    },
    history: {
      title:       'Calculation history',
      subtitle:    'View and manage all recorded calculations',
      noHistory:   'No calculations recorded',
      noHistorySub:'Run your first calculation to see it here.',
      exportPDF:   'Export PDF',
      clearAll:    'Clear all',
      search:      'Search employee...',
      month:       'Month',
      year:        'Year',
      reset:       'Reset',
    },
    login: {
      title:    'Welcome to ABC DIS',
      subtitle: 'HR & Commissions Management System',
      email:    'Email address',
      password: 'Password',
      submit:   'Sign in',
      loading:  'Signing in...',
      error:    'Incorrect email or password',
    },
    constraints: {
      title:          'Commission Rules',
      subtitle:       "Manage calculation rules by card (Coca Cola, Ferrero, Wall's)",
      newRule:        'New Rule',
      searchPlaceholder: 'Search a rule or condition...',
      allCards:       'All Cards',
      colName:        'Name',
      colCard:        'Card',
      colValue:       'Value',
      colCondition:   'Condition',
      colStatus:      'Status',
      colActions:     'Actions',
      noRules:        'No rules found.',
      deleteTitle:    'Delete rule',
      deleteDesc:     'Are you sure you want to delete this rule? This action is irreversible.',
      cancel:         'Cancel',
      confirmDelete:  'Confirm deletion',
      historyTooltip: 'View history',
      editTooltip:    'Edit',
      deleteTooltip:  'Delete',
    },
    calculation: {
      title:           'Calculation by Brand',
      subtitle:        'Choose a brand to access the specific calculation or import your data.',
      importBtn:       'Import Excel file',
      openManagement:  'Open management',
      sector:          'Distribution Sector',
      brandDescCoca:   'Delivery and commission management for the Coca-Cola range.',
      brandDescWalls:  "Seasonal commission and volume calculation for Wall's.",
      brandDescFerrero:'Objective tracking and bonuses for Ferrero products.',
    },
    personnel: {
      title:          'Personnel Management',
      subtitle:       'Manage and view team profiles',
      addProfile:     'Add profile',
      presenceSheet:  'Attendance Sheet',
      searchByName:   'Search by name...',
      activeFilter:   'Active',
      reset:          'Reset',
      loading:        'Loading...',
      noPersonnel:    'No personnel found',
      actif:          'Active',
      inactif:        'Inactive',
      activate:       'Activate',
      deactivate:     'Deactivate',
      edit:           'Edit',
      deleteTitle:    'Delete this profile?',
      deleteDesc:     'This action is irreversible. The profile will be permanently deleted.',
      addTitle:       'Add profile',
      editTitle:      'Edit profile',
      formDesc:       'Fill in the personnel information',
      update:         'Update',
      add:            'Add',
      matricule:      'Employee ID',
      contractType:   'Contract Type',
      nom:            'Last name',
      prenom:         'First name',
      carte:          'Card',
      fonction:       'Function',
      role:           'Role',
      telephone:      'Phone',
      ville:          'City',
      statut:         'Status',
      chooseCard:     'Choose a card',
      presenceTitle:  'Attendance Sheet',
      presenceDesc:   "Record delivery staff attendance for today's round.",
      truckId:        'Truck ID',
      canal:          'Channel',
      livreur:        'Driver',
      aide:           'Driver Assistant',
      none:           'None',
      save:           'Save',
    },
    brandCalc: {
      teamMembers:  'Team members',
      active:       'Active',
      noCalc:       'No calculation done',
      noCalcSub:    'Use the "Launch group calculation" button to simulate commissions.',
      launchBtn:    'Launch group calculation',
      calculating:  'Calculating...',
      detailTab:    'Detail by employee',
      recapTab:     'Global summary',
      commissions:  'Commissions',
      bonus:        'Bonus',
      penalties:    'Penalties',
      colEmployee:  'Employee',
      colBase:      'Base Sal.',
      colComm:      'Comm.',
      colBonus:     'Bonus',
      colPenal:     'Penal.',
      colNet:       'Net',
      teamTotal:    'TEAM TOTAL',
      back:         'Back',
    },
  },
} as const;

export type Translations = typeof translations['fr'];

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextValue | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('lang') as Lang) || 'fr';
  });

  const setLang = (l: Lang) => {
    localStorage.setItem('lang', l);
    setLangState(l);
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used inside LangProvider');
  return ctx;
}
